stages:
  - deploy
deploy_production2:
  stage: deploy
  script:
    - rsync -avzP * /opt/mobile/ --no-perms --no-owner --no-group
    - cd /opt/mobile/ && ls -l
    - ./gradlew build
    - cp build/libs/mobile.gtw.war ../webcontent
    - systemctl restart webapi
  environment:
    name: production2
  only:
    - master
deploy_develop:
  stage: deploy
  script:
    - rsync -avzP * /opt/dev_mobile/ --no-perms --no-owner --no-group
    - cd /opt/dev_mobile/ && ls -l
    - ./gradlew build
    - cp build/libs/mobile.gtw.war ../webcontent/dev-mobile.gtw.war
    - systemctl restart webapi
  environment:
    name: develop
  only:
    - dev
